"""
Formatting helpers — copy buttons, export, styling utilities.
"""

import streamlit as st
from datetime import datetime
from io import BytesIO


def copy_button(text: str, label: str = "Copy", key: str = ""):
    """Render a copy-to-clipboard button using st.code fallback."""
    with st.expander(f"{label} (click to copy)"):
        st.code(text, language="markdown")


def section_header(title: str, icon: str = ""):
    """Styled section header."""
    st.markdown(f"### {icon} {title}" if icon else f"### {title}")


def export_campaign_markdown(state: dict) -> str:
    """Export the full campaign to a well-formatted markdown file."""
    lines = []
    lines.append(f"# Neeman's Store Launch Campaign")
    lines.append(f"**Generated:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    lines.append(f"**City:** {state.get('city', 'N/A')}")
    lines.append(f"**Area:** {state.get('area', 'N/A')}")
    lines.append(f"**Opening Date:** {state.get('opening_date', 'N/A')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Research report
    if state.get("research_report"):
        lines.append("# Research Report")
        lines.append("")
        lines.append(state["research_report"])
        lines.append("")
        lines.append("---")
        lines.append("")

    # Campaign output
    if state.get("campaign_output"):
        lines.append("# Campaign Strategy & Assets")
        lines.append("")
        lines.append(state["campaign_output"])
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by Neeman's Store Launch Agent — Built with Claude API + Streamlit*")
    return "\n".join(lines)


def export_campaign_docx(state: dict) -> BytesIO:
    """Export campaign to DOCX format."""
    from docx import Document
    from docx.shared import RGBColor

    doc = Document()
    h = doc.add_heading("Neeman's Store Launch Campaign", level=0)
    for run in h.runs:
        run.font.color.rgb = RGBColor(0x1B, 0x3A, 0x2D)

    doc.add_paragraph(
        f"City: {state.get('city', 'N/A')} | "
        f"Area: {state.get('area', 'N/A')} | "
        f"Date: {state.get('opening_date', 'N/A')}"
    )
    doc.add_paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    doc.add_paragraph("")

    # Add research
    if state.get("research_report"):
        doc.add_heading("Research Report", level=1)
        for line in state["research_report"].split("\n"):
            stripped = line.strip()
            if stripped.startswith("## "):
                doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith("### "):
                doc.add_heading(stripped[4:], level=3)
            elif stripped.startswith("- ") or stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped:
                doc.add_paragraph(stripped)

    # Add campaign
    if state.get("campaign_output"):
        doc.add_page_break()
        doc.add_heading("Campaign Strategy & Assets", level=1)
        for line in state["campaign_output"].split("\n"):
            stripped = line.strip()
            if stripped.startswith("# "):
                doc.add_heading(stripped[2:], level=1)
            elif stripped.startswith("## "):
                doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith("### "):
                doc.add_heading(stripped[4:], level=3)
            elif stripped.startswith("- ") or stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped:
                doc.add_paragraph(stripped)

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
